server {
    listen 80;
    server_name seramono.mooo.com;

    location / {
        proxy_pass https://sera-agent.github.io/site/;
        proxy_set_header Host sera-agent.github.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Required for GitHub Pages
        proxy_ssl_server_name on;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/seramono.mooo.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/seramono.mooo.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = seramono.mooo.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name seramono.mooo.com;
    return 404; # managed by Certbot
}
